name: ">> Update Changelog for Dependabot PRs"

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - '**'

jobs:
  update_changelog:
    permissions:
      contents: write
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update CHANGELOG.md
        run: |
          # Ensure the changelog has an Unreleased section
          if ! grep -q "## Unreleased" CHANGELOG.md; then
            echo -e "## Unreleased\n\n" > tmpfile
            cat CHANGELOG.md >> tmpfile
            mv tmpfile CHANGELOG.md
          fi

          # Ensure a Dependencies section exists under Unreleased
          if ! grep -q "### Dependencies" CHANGELOG.md; then
            sed -i '/## Unreleased/a\\n### Dependencies\n' CHANGELOG.md
          fi

          # Insert PR title under the Dependencies section
          sed -i '/### Dependencies/a\- ${{ github.event.pull_request.title }}' CHANGELOG.md

          git config --global user.email "49699333+dependabot[bot]@users.noreply.github.com"
          git config --local user.name "Dependabot"
          git add CHANGELOG.md
          git commit -m "[Auto-CHANGELOG] Dependabot: ${{ github.event.pull_request.title }}"

      - name: Push changes
        run: |
          git push origin ${{ github.event.pull_request.head.ref }}
